Adding more in

diff --git a/script/bootstrap b/script/bootstrap
--- a/script/bootstrap
+++ b/script/bootstrap
@@ -27,27 +27,27 @@ fail () {
   exit
 }
 
-setup_gitconfig () {
-  if ! [ -f git/gitconfig.local.symlink ]
-  then
-    info 'setup gitconfig'
-
-    git_credential='cache'
-    if [ "$(uname -s)" == "Darwin" ]
-    then
-      git_credential='osxkeychain'
-    fi
-
-    user ' - What is your github author name?'
-    read -e git_authorname
-    user ' - What is your github author email?'
-    read -e git_authoremail
-
-    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink
-
-    success 'gitconfig'
-  fi
-}
+# setup_gitconfig () {
+#   if ! [ -f git/gitconfig.local.symlink ]
+#   then
+#     info 'setup gitconfig'
+# 
+#     git_credential='cache'
+#     if [ "$(uname -s)" == "Darwin" ]
+#     then
+#       git_credential='osxkeychain'
+#     fi
+# 
+#     user ' - What is your github author name?'
+#     read -e git_authorname
+#     user ' - What is your github author email?'
+#     read -e git_authoremail
+# 
+#     sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink
+# 
+#     success 'gitconfig'
+#   fi
+# }
 
 
 link_file () {
@@ -55,20 +55,20 @@ link_file () {
 
   local overwrite= backup= skip=
   local action=
-
+  
+  # If $dst is a file, directory, or symbolic link, choose 
+  # whether to skip this file.
   if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
   then
 
     if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
     then
 
+      # If $dst is already a link to $src then we can skip.
       local currentSrc="$(readlink $dst)"
-
       if [ "$currentSrc" == "$src" ]
       then
-
         skip=true;
-
       else
 
         user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
@@ -137,20 +137,20 @@ install_dotfiles () {
   done
 }
 
-setup_gitconfig
+# setup_gitconfig
 install_dotfiles
 
-# If we're on a Mac, let's install and setup homebrew.
-if [ "$(uname -s)" == "Darwin" ]
-then
-  info "installing dependencies"
-  if source bin/dot | while read -r data; do info "$data"; done
-  then
-    success "dependencies installed"
-  else
-    fail "error installing dependencies"
-  fi
-fi
+# # If we're on a Mac, let's install and setup homebrew.
+# if [ "$(uname -s)" == "Darwin" ]
+# then
+#   info "installing dependencies"
+#   if source bin/dot | while read -r data; do info "$data"; done
+#   then
+#     success "dependencies installed"
+#   else
+#     fail "error installing dependencies"
+#   fi
+# fi
 
 echo ''
 echo '  All installed!'
